name: Robot Framework Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Robot Framework tests
      run: robot --variable BROWSER:headlesschrome --outputdir results test.robot

    - name: Upload Robot Framework results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: robot-framework-results
        path: results/
